### PR TITLE
Update formatting for `.ts` and `.json` files in `apps/vscode/`

### PR DESCRIPTION
**Pull request by juliasilge**
This PR updates the formatting on `.ts` and `.json` to use the workspace settings, so we don't continue to have so much extraneous whitespace change in PRs like #589.

### CODE REVIEW

**Comment by DavisVaughan** [comment]
eep let us merge in the existing ones first!

**Comment by juliasilge** [comment]
Wait for #577 to be merged, before merging this one (I think #585 will be easy to resolve)

**Comment by DavisVaughan** [comment]
We should also see if we can set these

```
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
```

at the very least, trim trailing whitespace would be nice

**Comment by juliasilge** [comment]
This one is now ready for a review and to be merged. Here's to making things less painful moving forward! 🙌

**Review by cscheid — APPROVED** [review]
LGTM!

**Pull request merged**
