### PR TITLE
Add GH action to generate `.vsix` artifact

### PR DESCRIPTION
**Pull request by juliasilge**
Let's see how many tries it takes me to get this to work. 🤞

### CODE REVIEW

**Comment by juliasilge** [comment]
Only three tries?! Maybe a record for me with GH actions.

**Comment by juliasilge** [comment]
You can go to the [page for an action run](https://github.com/quarto-dev/quarto/actions/runs/8992442652) to find the link for the `.vsix` and download it. We could eventually publish these as part of a release to surface them more, but for our development work, I think this is the best option.

After that, you can install it via "Extensions: Install from VSIX..." command.

**Comment by cscheid** [comment]
I agree that not advertising releases is still the best way to go about this.

**Review by cscheid — APPROVED** [review]
Looks good!

**Pull request merged**
